<a href="https://colab.research.google.com/github/murrashovaa/Structures-and-algorithmes/blob/main/CourseWork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Курсовая работа по СиАОД
### Выполнила студентка группы БСТ2105 Мурашова В.А.
### Проверил Павликов А.Е.

### Задание

Написать программу, которая будет считывать данные из CSV файла, содержащего информацию о продажах товаров в магазине. Данные в файле содержатся в следующем формате: | Номер заказа | Дата заказа | Название товара | Категория товара | Количество продаж | Цена за единицу | Общая стоимость 

Необходимо:

Рассчитать общую выручку магазина.
Найти товар, который был продан наибольшее количество раз.
Найти товар, который принес наибольшую выручку.
Составить отчет, содержащий информацию об общей выручке магазина, количестве
проданных единиц каждого товар и доле каждого товара в общей выручке.

### Выполнение

In [ ]:
import csv
import pandas as pd

#### Исходная таблица

In [ ]:
df = pd.read_csv("table.csv", delimiter=';', index_col='Номер заказа')
df

,Дата заказа,Название товара,Категория товара,Количество продаж,Цена за единицу,Общая стоимость
Номер заказа,,,,,,
4001,01.02.2022,Apple iPhone 14,Смартфоны,500,89990,44995000
4002,02.04.2022,Samsung Galaxy S22 Ultra,Смартфоны,300,99990,29997000
4003,03.01.2022,Игровые приставки,Игровые приставки,200,59990,11998000
4004,04.02.2022,LG OLED TV,Телевизоры,150,179990,26998500
4005,05.05.2022,Apple MacBook Pro 16,Ноутбуки,100,199990,19999000
4006,06.03.2022,Canon EOS R7,Фотоаппараты,50,249990,12499500
4007,07.06.2022,Bose QuietComfort 55,Наушники,100,34990,3499000
4008,08.05.2022,Samsung Galaxy Tab S8,Планшеты,75,69990,5249250
4009,09.04.2022,DJI Mavic 3,Дроны,25,149990,3749750
4010,10.02.2022,Philips Hue Smart Bulbs,Умный дом,500,2990,1495000
5001,01.01.2022,Apple iPad Pro 12.9,Планшеты,200,89990,17998000
5002,02.02.2022,Sony PlayStation 5 Pro,Игровые приставки,100,59990,5999000
5003,03.10.2022,Samsung Galaxy Watch 5,Умные часы,150,29990,4498500
5004,04.11.2022,LG UltraFine,Мониторы,50,99990,4999500
5005,05.12.2022,Canon EOS R8,Фотоаппараты,75,299990,22499250
5006,06.10.2021,Bose SoundLink Revolve+,Портативные колонки,100,24990,2499000
5007,07.09.2022,DJI Ronin 4D,Стабилизаторы,25,499990,12499750
5008,08.07.2021,Samsung Galaxy Book Pro,Ноутбуки,50,129990,6499500
5009,09.07.2022,Philips Sonicare DiamondClean,Электрические зубные щетки,200,9990,1998000
5010,10.02.2001,Nest Learning Thermostat,Умный дом,100,19990,1999000

In [ ]:
class Item:

    def __init__(self, attributes: list):
        order_number, order_date, product_name, category, sales_quantity, price_per_unit, total_cost = attributes
        self.order_number = order_number
        self.order_date = order_date
        self.product_name = product_name
        self.category = category
        self.sales_quantity = int(sales_quantity)
        self.price_per_unit = int(price_per_unit)
        self.total_cost = int(total_cost)


class Table:

    def __init__(self, items: list):
        self.items = items
        self.item_get_col = {  # словарь для получения значений item в get_column
            'order_number': lambda x: x.order_number,
            'order_date': lambda x: x.order_date,
            'product_name': lambda x: x.product_name,
            'category': lambda x: x.category,
            'sales_quantity': lambda x: x.sales_quantity,
            'price_per_unit': lambda x: x.price_per_unit,
            'total_cost': lambda x: x.total_cost
        }

    def get_size(self) -> int:
        return len(self.items)

    def get_column(self, column: str) -> list:
        if column not in self.item_get_col.keys():
            return []
        ans = []
        get_lambda = self.item_get_col[column]
        for item in self.items:
            ans.append(get_lambda(item))
        return ans

    def get_column_sum(self, column) -> float:
        try:
            return sum(self.get_column(column))
        except:
            return None

    def find_maximum(self, column: list) -> float:
        max = 0
        for item in column:
            if item > max:
                max = item
        return max


class Report:

    def __init__(self, table):
        self.table = table

    def _profit(self) -> float:
        return self.table.get_column_sum('total_cost')

    def _sales_num(self) -> int:
        return self.table.get_column_sum('sales_quantity')

    def _percent(self, cost: float, profit: float) -> float:
        return round(cost / profit * 100, 2)

    def _most_freq_item(self) -> tuple[list, int]:
        quantity = self.table.find_maximum(self.table.get_column('sales_quantity'))
        ans = []
        ls = self.table.items
        for item in ls:
            if item.sales_quantity == quantity:
                ans.append(item.product_name)
        return (ans, quantity)

    def _most_prof_item(self) -> tuple[list, float]:
        profit = self.table.find_maximum(self.table.get_column('total_cost'))
        ans = []
        ls = self.table.items
        for item in ls:
            if item.total_cost == profit:
                ans.append(item.product_name)
        return (ans, profit)

    def _make_dataframe(self):
        p = []
        total = self._profit()
        n = self.table.get_column('product_name')
        q = self.table.get_column('sales_quantity')
        t = self.table.get_column('total_cost')
        for cost in t:
            p.append(self._percent(cost, total))

        df = pd.DataFrame({'Количество проданных единиц, шт': q,
                           'Общая сумма продаж, руб': t,
                           'Доля товара в общей выручке, %': p}, index=n)
        display(df.sort_values("Общая сумма продаж, руб", ascending=False))

    def make(self):
        print("Отчёт:")
        print(f'Общая выручка магазина составляет  = {self._profit()} руб, ' +
              f'всего товаров продано {self._sales_num()} шт')
        print(
            f'Наибольший объем продаж у товаров: {", ".join(self._most_freq_item()[0])}, {self._most_freq_item()[1]} шт')
        print(f'Наибольшая выручка у товаров: {", ".join(self._most_prof_item()[0])}, {self._most_prof_item()[1]} руб"')
        self._make_dataframe()

In [ ]:
with open("table.csv", mode="r", encoding="utf-8") as f:
    reader = csv.reader(f, delimiter=";")
    header = next(reader) # пропуск первой строчки
    items = []
    for row in reader:
        items.append(Item(row))
        
products_table = Table(items)
report = Report(products_table)
report.make()

Отчёт:
Общая выручка магазина составляет  = 241969500 руб, всего товаров продано 3050 шт
Наибольший объем продаж у товаров: Apple iPhone 14, Philips Hue Smart Bulbs, 500 шт
Наибольшая выручка у товаров: Apple iPhone 14, 44995000 руб"

,"Количество проданных единиц, шт","Общая сумма продаж, руб","Доля товара в общей выручке, %"
Apple iPhone 14,500,44995000,18.60
Samsung Galaxy S22 Ultra,300,29997000,12.40
LG OLED TV,150,26998500,11.16
Canon EOS R8,75,22499250,9.30
Apple MacBook Pro 16,100,19999000,8.27
Apple iPad Pro 12.9,200,17998000,7.44
DJI Ronin 4D,25,12499750,5.17
Canon EOS R7,50,12499500,5.17
Игровые приставки,200,11998000,4.96
Samsung Galaxy Book Pro,50,6499500,2.69
Sony PlayStation 5 Pro,100,5999000,2.48
Samsung Galaxy Tab S8,75,5249250,2.17
LG UltraFine,50,4999500,2.07
Samsung Galaxy Watch 5,150,4498500,1.86
DJI Mavic 3,25,3749750,1.55
Bose QuietComfort 55,100,3499000,1.45
Bose SoundLink Revolve+,100,2499000,1.03
Nest Learning Thermostat,100,1999000,0.83
Philips Sonicare DiamondClean,200,1998000,0.83
Philips Hue Smart Bulbs,500,1495000,0.62

### Вывод

Была написана программа, которая считывает данные из CSV файла, содержащего информацию о продажах товаров в магазине, был составлен отчёт: рассчитана общая выручка магазина, были найдены товары с наибольшим числом продаж и товар с наибольшей выручкой, с помощью библиотеки Pandas была составлена таблица, в которой представлены товары магазина, отсортированные по доле в общей выручке магазина. Проект был загружен на Github: https://github.com/murrashovaa/Structures-and-algorithmes